In [ ]:
import numpy

In [1]:
import numpy 
arr = numpy.array([1,2,3,4,5])

print(arr)


[1 2 3 4 5]


In [2]:
import numpy as np 
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [3]:
print(np.__version__)

1.20.1


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
tmp = np.ndarray([1,2,3,4,5])
print(tmp)

[[[[[6.95248389e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
     0.00000000e+000]
    [4.94065646e-324 0.00000000e+000 0.00000000e+000 0.00000000e+000
     0.00000000e+000]
    [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
     0.00000000e+000]
    [0.00000000e+000 0.00000000e+000 6.95248398e-310 0.00000000e+000
     0.00000000e+000]]

   [[0.00000000e+000 0.00000000e+000 0.00000000e+000 1.42173718e-312
     0.00000000e+000]
    [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
     0.00000000e+000]
    [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
     0.00000000e+000]
    [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
     0.00000000e+000]]

   [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
     0.00000000e+000]
    [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
     0.00000000e+000]
    [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
     0.00000000e+

In [7]:
# dimensions in Arrays.
# 0-D array (Scalar).
import numpy as np
arr = np.array(36)

print(arr)

36


In [8]:
# 1-D array.
import numpy as np
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [9]:
# 2-D array.
import numpy as np
arr = np.array([ [1,2,3], [4,5,6] ] )

print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
# 3-D array.
import numpy as np
arr = np.array([ [ [1,2,3], [4,5,6], [7,8,9], [10,11,12] ] ])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [11]:
print(arr[0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
print(arr[0][0])

[1 2 3]


In [13]:
print(arr[0][0][0])

1


In [14]:
print(arr[0][1])

[4 5 6]


In [15]:
print(arr[0][2])

[7 8 9]


In [16]:
print(arr[0][3])

[10 11 12]


In [21]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [24]:
print(arr[0][3][2])
print(arr[0,3,2])

12
12


In [19]:
tmp = np.array([1,2, "abc", "def"])

In [20]:
print(tmp)

['1' '2' 'abc' 'def']


In [22]:
print(arr.ndim)

3


In [23]:
a = np.array(57)
b = np.array([1,2,3,4,5])
c = np.array([ [1,2,3], [4,5,6]])
d = np.array([[ [1,2,3], [4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [25]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [26]:
arr = np.array([1,2,3,4])

print(arr[2] + arr[3])

7


In [29]:
import numpy as np
arr2 = np.array([[1,2,3], [4,5,6]], ndmin=5)
print(arr2)
print(arr2.ndim)

[[[[[1 2 3]
    [4 5 6]]]]]
5


In [28]:
arr = np.array([[ [1,2,3], [4,5,6], [7,8,9]]])
print(arr)
print(arr[0])
print(arr[0][1])
print(arr[0][1][2])


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6


In [31]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10] ])
print(arr.ndim)
print(arr[1,-1])
print(arr[1,-3])
print(arr[0,-3])


2
10
8
3


In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])

[2 3 4 5]


In [33]:
print(arr[1:8])
print(arr[1:8:2])
print(arr[0:8:2])

[2 3 4 5 6 7 8]
[2 4 6 8]
[1 3 5 7]


In [34]:
print(arr[1:8:3])

[2 5 8]


In [35]:
print(arr[4:])

[ 5  6  7  8  9 10]


In [36]:
print(arr[:4])

[1 2 3 4]


In [37]:
print(arr[-3:-1])

[8 9]


In [38]:
print(arr[::2])

[1 3 5 7 9]


In [40]:
arr = np.array( [ [1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 1:4])   # 2,3,4 OR 7,8,9,10 OR 7,8,9
print(arr[0][1:4])

[2 3 4]
[2 3 4]


In [43]:
print(arr)
print(arr[0:2])
print(arr[0:2,2])     # arr[0:2][2]     prints 3,8

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 8]


In [46]:
print(arr)
print(arr[0:2][1:4])     # not preferred.


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 6  7  8  9 10]]


In [45]:
print(arr[0:2,1:4])     # preferred.

[[2 3 4]
 [7 8 9]]


In [47]:
arr = np.array([1,2,3,4,5])
newArr = arr.copy()

print(arr)
print(newArr)

[1 2 3 4 5]
[1 2 3 4 5]


In [48]:
arr[0] = 76
print(arr)
print(newArr)

[76  2  3  4  5]
[1 2 3 4 5]


In [49]:
newArr[2] = 50
print(arr)
print(newArr)

[76  2  3  4  5]
[ 1  2 50  4  5]


In [50]:
arr = np.array([1,2,3,4,5])
newArr = arr.view()

print(arr)
print(newArr)

[1 2 3 4 5]
[1 2 3 4 5]


In [51]:
arr[0] = 76
print(arr)
print(newArr)

[76  2  3  4  5]
[76  2  3  4  5]


In [52]:
newArr[2] = 50
print(arr)
print(newArr)

[76  2 50  4  5]
[76  2 50  4  5]


In [53]:
arr = np.array([1,2,3,4,5])

copyArr = arr.copy()
viewArr = arr.view()

print(copyArr)
print(viewArr)

# If it returns "None", it is a copy and owns the data.
print(copyArr.base)    
print(viewArr.base)


[1 2 3 4 5]
[1 2 3 4 5]
None
[1 2 3 4 5]


In [54]:
# Iterating.
arr = np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [55]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [56]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [57]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [58]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
for indx, x in np.ndenumerate(arr):
    print(indx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(0, 2, 0) 11
(0, 2, 1) 12
(0, 2, 2) 13
(0, 2, 3) 14
(0, 2, 4) 15


In [59]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [65]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [66]:
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [69]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.stack((arr1,arr2), axis=1)
print(arr)

names1 = np.array(["John", "Joe", "Mary"])
names2 = np.array(["Michael", "Max", "Terry"])
new_names = np.stack((names1,names2), axis=1)
print(new_names)


[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[['John' 'Michael']
 ['Joe' 'Max']
 ['Mary' 'Terry']]


In [70]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.stack((arr1,arr2))
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [71]:
arr1 = np.array([1,2,3,4,5,6])

arr = np.array_split(arr1,3)
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [72]:
arr1 = np.array([1,2,3,4,5,6,7])

arr = np.array_split(arr1,3)
print(arr)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [73]:
arr1 = np.array([1,2,3,4,5,6])

arr = np.array_split(arr1,4)
print(arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [74]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])


[1 2]
[3 4]
[5]
[6]


In [75]:
arr1 = np.array([[1,2],[3,4], [5,6],[7,8], [9,10]])

arr = np.array_split(arr1, 3)
print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]])]


In [77]:
arr = np.array([1,2,3,4,5,6,7])
srch = np.where(arr == 4)
print(srch)
print(type(srch))

(array([3], dtype=int64),)
<class 'tuple'>


In [78]:
arr = np.array([1,2,3,4,5,4,6,7,4])
srch = np.where(arr == 4)
print(srch)

(array([3, 5, 8], dtype=int64),)


In [79]:
print(arr[srch])

[4 4 4]


In [81]:
arr = np.array([1,2,3,4,5,6,7,8])
srch = np.where(arr % 2 == 0)
print(srch)
print(arr[srch])

(array([1, 3, 5, 7], dtype=int64),)
[2 4 6 8]


In [82]:
arr = np.array([1,2,3,4,5,6,7,8])
srch = np.where(arr % 2 == 1)
print(srch)
print(arr[srch])

(array([0, 2, 4, 6], dtype=int64),)
[1 3 5 7]


In [83]:
arr = np.array([5,6,8,9])
x = np.searchsorted(arr, 7)
print(x)


2


In [84]:
arr = np.array([8,6,9,5])
x = np.searchsorted(arr, 7)
print(x)


2


In [85]:
arr = np.array([4,5,6,8,9])
x = np.searchsorted(arr, 7, side="right")
print(x)


3


In [86]:
arr = np.array([1,3,5,7])
x = np.searchsorted(arr, [2,4])
print(x)


[1 2]


In [87]:
arr1 = np.array([8,6,9,5])
arr = np.sort(arr1)

print(arr)

[5 6 8 9]


In [88]:
arr1 = np.array(["strawberry", "apple", "orange", "banana",])
arr = np.sort(arr1)

print(arr)

['apple' 'banana' 'orange' 'strawberry']


In [89]:
arr1 = np.array([15,16,17,18])
filter = [True, False, True, False]

newArr = arr1[filter]
print(newArr)

[15 17]


In [90]:
arr1 = np.array([15,16,17,18])
filter = [True, False, False, True]

newArr = arr1[filter]
print(newArr)

[15 18]


In [91]:
arr1 = np.array([15,16,17,18])
filter = [True, False, False, True]

newArr = arr1[filter]
print(newArr)

[15 18]


In [92]:
arr1 = np.array([15,16,17,18, 19, 20])
filter = arr1 > 18

newArr = arr1[filter]
print(filter)
print(newArr)

[False False False False  True  True]
[19 20]


In [93]:
arr1 = np.array([15,16,17,18, 19, 20])
filter = arr1 %2 == 0

newArr = arr1[filter]
print(filter)
print(newArr)

[False  True False  True False  True]
[16 18 20]
